name: Bump Tag

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  prebuild:
    uses: ./.github/workflows/commit_msg.yml

  bump_tag:
    runs-on: ubuntu-latest

    needs:
      - prebuild

    if: ${{ contains(needs.prebuild.outputs.commit_msg, '[ci release]') }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          WITH_V: true
          RELEASE_BRANCHES: "master"