name: Bump Tag

on:
  workflow_call:
    inputs:
      release_branches:
        type: string
        default: "master"
        description: "Release branches"
        required: false
      with_v:
        type: boolean
        default: true
        description: "Append v prefix to version"
        required: false
    secrets:
      token:
        required: true

jobs:
  prebuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - if: github.event_name == 'push'
        id: push_commit_msg
        run: echo ::set-output name=push_msg::$(git log --format=%B -n 1 HEAD)

      - if: github.event_name == 'pull_request'
        id: pull_commit_msg
        run: echo ::set-output name=pull_msg::$(git log --format=%B -n 1 HEAD^2)

    outputs:
      commit_msg: $( [ -z "${{ steps.pull_commit_msg.outputs.pull_msg }}" ] && echo "${{ steps.push_commit_msg.outputs.push_msg }}" || echo "${{ steps.pull_commit_msg.outputs.pull_msg }}" )


  bump_tag:
    runs-on: ubuntu-latest

    needs:
      - prebuild

    if: ${{ contains(needs.prebuild.outputs.commit_msg, '[ci release]') }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          WITH_V: true
          RELEASE_BRANCHES: "master"