name: Lint

on:
  workflow_call:
    secrets:
      github_token:
        required: true

jobs:
  prebuild:
    uses: ./.github/workflows/commit_msg.yml

  lint:
    needs:
      - prebuild

    if: ${{ !contains(needs.prebuild.outputs.commit_msg, '[ci nolint]') }}

    strategy:
      matrix:
        go-version:
          - 1.17.x
          - 1.18.x
        platform:
          - ubuntu-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go modules cache
        id: mod_cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go${{ matrix.go-version }}-

      - name: Go Mod Download
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version:      v1.46.2
          skip-cache:   true
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}