name: "Archive Release"

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      archive_files:
        type: string
        default: |
          *.go
          go.mod
          go.sum
          LICENSE
        description: "List of files"
        required: false
    secrets:
      token:
        required: true
      gpg_secret_key:
        required: true
      gpg_password:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id:   git_tag
        run:  echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - id: tarball_file
        run: |
          TARBALL=${{ inputs.package_name }}_${{ steps.git_tag.outputs.tag }}.tar.gz
          echo ::set-output name=filename::${TARBALL}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.gpg_secret_key }}
          passphrase:      ${{ secrets.gpg_password }}

      - name: Build dist tarball
        run: tar -czvf ${{ steps.tarball_file.outputs.filename }} ${{ inputs.archive_files }}

      - name: GPG sign dist tarball
        run: gpg --armor --detach-sign ${{ steps.tarball_file.outputs.filename }}

      - name: Create and publish GitHub release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.token }}
          prerelease: false
          files: |
            ${{ steps.tarball_file.outputs.filename }}
            ${{ steps.tarball_file.outputs.filename }}.asc
            LICENSE