name: Test

on:
  workflow_call:

jobs:
  prebuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - if: github.event_name == 'push'
        id: push_commit_msg
        run: echo ::set-output name=push_msg::$(git log --format=%B -n 1 HEAD)

      - if: github.event_name == 'pull_request'
        id: pull_commit_msg
        run: echo ::set-output name=pull_msg::$(git log --format=%B -n 1 HEAD^2)

    outputs:
      commit_msg: $( [ -z "${{ steps.pull_commit_msg.outputs.pull_msg }}" ] && echo "${{ steps.push_commit_msg.outputs.push_msg }}" || echo "${{ steps.pull_commit_msg.outputs.pull_msg }}" )

  test:
    needs:
      - prebuild

    if: ${{ !contains(needs.prebuild.outputs.commit_msg, '[ci notest]') }}

    strategy:
      matrix:
        go-version:
          - 1.17.x
          - 1.18.x
        platform:
          - ubuntu-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go modules cache
        id: mod_cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go${{ matrix.go-version }}-

      - name: Go Mod Download
        run: go mod download

      - name: Run tests
        run: go test ./...